packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # all packages in subdirs of components/
  - 'api/**'
  # all packages in subdirs of components/
  - 'utils/**'
  # exclude packages that are inside test directories
  - '!**/test/**'